# Telling to use Docker's golang ready image
FROM golang
# Create app folder 
RUN mkdir /app
# Copy our file in the host contianer to our contianer
ADD . /app
# Set /app to the go folder as workdir
WORKDIR /app
# Generate binary file from our /app
RUN go build
# Expose the port 8080
# Expose 8080:8080
EXPOSE 8080
# Run the app binary file 
CMD ["./app"]