#first stage - builder
FROM golang:1.13.0-alpine as builder
ADD . /app
WORKDIR /app
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o /main .
#second stage
FROM alpine:latest
ENV PORT="6000"
COPY --from=builder /main .
CMD ["./main"]
EXPOSE 6000